### ISSUE TITLE
ImportError: No module named rosdistro

### ISSUE THREAD

**Issue by Theosakamg** [rosjava/genjava#5]
When i compile my java messages on ROS build farm.
(but working on local workspace)

==> make -j1 in '/tmp/catkin_workspace/build_isolated/smarthome_media_msgs_java'
Scanning dependencies of target smarthome_media_msgs_java_generate_artifacts
[100%] Compiling rosjava message artifacts for [smarthome_media_msgs]
Traceback (most recent call last):
  File "/opt/ros/indigo/share/genjava/cmake/../../../lib/genjava/genjava_message_artifacts", line 11, in <module>
    import genjava
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/**init**.py", line 39, in <module>
    from .genjava_main import main, standalone_main
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/genjava_main.py", line 45, in <module>
    import rosjava_build_tools
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosjava_build_tools/**init**.py", line 12, in <module>
    from release import scrape_for_release_message_packages
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosjava_build_tools/release.py", line 7, in <module>
    import rosdistro
ImportError: No module named rosdistro
make[2]: **\* [CMakeFiles/smarthome_media_msgs_java_generate_artifacts] Error 1
make[1]: **\* [CMakeFiles/smarthome_media_msgs_java_generate_artifacts.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'smarthome_media_msgs_java':

For : https://github.com/rosalfred/smarthome_media_msgs_java
Job : http://build.ros.org/job/Idev__smarthome_media_msgs_java__ubuntu_trusty_amd64/2/console

Any idea ?
Thank.

**Comment by Theosakamg** [comment]
After many test need to add in package.xml :

```
<!-- needed for genjava rosdistro dependency -->
<build_depend>python-rosdistro</build_depend>
<!-- needed for genjava roslib dependency -->
<build_depend>roslib</build_depend>
```
